description: >- 
  TF Learnpath is a module to display lessons inside a course using the TF Learn component in Joomla!
url: "https://naftee.com"
baseurl: "/TfLearnpath"
github_username: brettvac

author:
  twitter: naftee
  name: Brett Vachon

google_analytics: G-DP5DG417G7

remote_theme: zivhub/monophase@main

lang: en_GB
timezone: America/Toronto

plugins:
  - jekyll-remote-theme 
  - jekyll-seo-tag
  - jekyll-sitemap
